url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "argueta I/O" # the name of your site, e.g. ACME Corp.
# sass:
#   style: compressed